export const errorCodes = {
  // Typography
  TYP_TOO_SMALL: "TYP-001",
  TYP_INVALID_WEIGHT: "TYP-002",
  TYP_INVALID_LINEHEIGHT: "TYP-003",
  TYP_HEADING_JUMP: "TYP-004",

  // Spacing
  SPC_NOT_GRID: "SPC-001",
  SPC_ILLEGAL_VALUE: "SPC-002",
  SPC_INCONSISTENT_SIBLING: "SPC-003",

  // Layout
  LAY_OVERFLOW: "LAY-001",
  LAY_ALIGNMENT: "LAY-002",
  LAY_FRAME_TOO_WIDE: "LAY-003",
  LAY_FRAME_TOO_NARROW: "LAY-004",

  // Geometry
  GEO_ICON_TOO_SMALL: "GEO-001",
  GEO_BUTTON_PADDING: "GEO-002",
  GEO_RADIUS_INVALID: "GEO-003",

  // Visual
  VIS_ILLEGAL_SURFACE: "VIS-001",
  VIS_FORBIDDEN_EFFECT: "VIS-002",
};

