// scripts/sync-mcp-prompt.ts
import fs from "node:fs";
import path from "node:path";

const promptPath = path.join(process.cwd(), "tools", "MCP_SYSTEM_PROMPT.md");
const outputPath = path.join(
  process.cwd(),
  ".mcp",
  "ui-generator",
  "systemPrompt.generated.ts",
);

function main() {
  if (!fs.existsSync(promptPath)) {
    console.error(
      `[sync-mcp-prompt] Missing MCP_SYSTEM_PROMPT.md at ${promptPath}`,
    );
    process.exit(1);
  }

  const content = fs.readFileSync(promptPath, "utf8");

  const file = `// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by: pnpm sync-mcp-prompt
// Source: tools/MCP_SYSTEM_PROMPT.md

export const UI_GENERATOR_SYSTEM_PROMPT = ${JSON.stringify(content)};

`;

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, file, "utf8");

  console.log(
    `[sync-mcp-prompt] Synced MCP system prompt to ${path.relative(
      process.cwd(),
      outputPath,
    )}`,
  );
}

main();
